import type { Metadata } from "next";;
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Inter, Roboto, Poppins } from 'next/font/google';




// Define fonts with subsets for optimization
const inter = Inter({ subsets: ['latin'], weight: ['700'], variable: '--font-inter' });
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500'], variable: '--font-roboto' });
const poppins = Poppins({ subsets: ['latin'], weight: ['600'], variable: '--font-poppins' });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto.variable} ${poppins.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
